<?php

namespace App\Models;

use App\Models\Scopes\SubCategoryScope;

class SubCategory extends Category
{

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::addGlobalScope(SubCategoryScope::class);
    }
}
